title: "Christopher Maier's Technical Blog"
email: ""
description: >
  Miscellaneous writings from a software engineer
baseurl: ""
url: "http://christophermaier.name"
twitter_username: _cwm_
github_username: christophermaier
disqus:
    shortname: christophermaier
google_analytics: UA-18090378-1
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
permalink: pretty
defaults:
  - scope:
      path: _posts
    values:
      layout: post
      comments: true
      author: Christopher Maier
